version: "3"
services:
  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8555:8555
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react:
